#############################################################################
# Makefile for building: Boid
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Boid.pro
# Template: app
# Command: /Users/nikithaanngeorge/Qt5.8.0/5.8/clang_64/bin/qmake -o Makefile Boid.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT5BUILD -DGL_SILENCE_DEPRECATION -DQT5BUILD -DFMT_HEADER_ONLY -DUSEGLM -DGLM_ENABLE_EXPERIMENTAL -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -arch x86_64 -g -std=gnu++1y -Wall -W -Wno-unused-parameter -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/usr/local/include -I/public/devel/include -I/Users/nikithaanngeorge/vcpkg/installed/x64-linux/include -I../../NGL/include -I../../NGL/gl3w -I../../Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/Headers -I../../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I../../Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -F/Users/nikithaanngeorge/Qt5.8.0/5.8/clang_64/lib
QMAKE         = /Users/nikithaanngeorge/Qt5.8.0/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Boid1.0.0
DISTDIR = /Users/nikithaanngeorge/GitHub/MyFirstQtProject/obj/Boid1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,@loader_path/L/Users/nikithaanngeorge/NGL/lib -Wl,-rpath,/Users/nikithaanngeorge/NGL/lib -Wl,-rpath,/Users/nikithaanngeorge/Qt5.8.0/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/nikithaanngeorge/Qt5.8.0/5.8/clang_64/lib -L/usr/local/lib -L/Users/nikithaanngeorge/vcpkg/installed/x64-linux/lib -L/Users/nikithaanngeorge/NGL/lib -l NGL -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/NGLScene.cpp \
		src/main.cpp 
OBJECTS       = obj/NGLScene.o \
		obj/main.o
DIST          = ../../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../NGL/UseNGL.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		Boid.pro include/NGLScene.h \
		include/WindowParams.h src/NGLScene.cpp \
		src/main.cpp
QMAKE_TARGET  = Boid
DESTDIR       = 
TARGET        = Boid


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Boid.pro .qmake.cache ../../Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../NGL/UseNGL.pri \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		Boid.pro \
		../../Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		../../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Boid.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../NGL/UseNGL.pri:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf:
../../Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf:
Boid.pro:
../../Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
../../Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Boid.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/NGLScene.h include/WindowParams.h $(DISTDIR)/
	$(COPY_FILE) --parents src/NGLScene.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: ../../Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -arch x86_64 -g -std=gnu++1y -Wall -W -Wno-unused-parameter -dM -E -o moc/moc_predefs.h ../../Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/NGLScene.o: src/NGLScene.cpp ../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		include/NGLScene.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/gl3w/gl3w.h \
		../../NGL/gl3w/glcorearb.h \
		../../NGL/include/ngl/fmt/format.h \
		../../NGL/include/ngl/fmt/format.cc \
		../../NGL/include/ngl/NGLMessage.h \
		../../NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		../../NGL/include/ngl/Vec2.h \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		../../NGL/include/ngl/Vec3.h \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		../../NGL/include/ngl/Vec4.h \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/detail/type_vec4_sse2.inl \
		/usr/local/include/glm/detail/type_vec4_avx.inl \
		/usr/local/include/glm/detail/type_vec4_avx2.inl \
		../../NGL/include/ngl/Mat4.h \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		include/WindowParams.h \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../NGL/include/ngl/NGLInit.h \
		../../NGL/include/ngl/Singleton.h \
		../../NGL/include/ngl/VAOPrimitives.h \
		../../NGL/include/ngl/VAOFactory.h \
		../../NGL/include/ngl/SimpleVAO.h \
		../../NGL/include/ngl/ShaderLib.h \
		../../NGL/include/ngl/Shader.h \
		../../NGL/include/ngl/ShaderProgram.h \
		../../NGL/include/ngl/Util.h \
		../../NGL/include/ngl/Mat2.h \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		../../NGL/include/ngl/Mat3.h \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/main.o: src/main.cpp include/NGLScene.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/gl3w/gl3w.h \
		../../NGL/gl3w/glcorearb.h \
		../../NGL/include/ngl/fmt/format.h \
		../../NGL/include/ngl/fmt/format.cc \
		../../NGL/include/ngl/NGLMessage.h \
		../../NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		../../NGL/include/ngl/Vec2.h \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		../../NGL/include/ngl/Vec3.h \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		../../NGL/include/ngl/Vec4.h \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/detail/type_vec4_sse2.inl \
		/usr/local/include/glm/detail/type_vec4_avx.inl \
		/usr/local/include/glm/detail/type_vec4_avx2.inl \
		../../NGL/include/ngl/Mat4.h \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		include/WindowParams.h \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLWindow \
		../../Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

